### ISSUE TITLE
Region is not configurable

### ISSUE THREAD

**Issue by Sleavely** [niradler/apigateway-export-tool#1]
It looks like the AWS region is hardcoded, making usage of this tool for projects hosted in EU or other places tricky.

https://github.com/niradler/apigateway-export-tool/blob/57b3841bbae97381fc0a3a972ddcec16abb30859/index.js#L6-L9

Consider making it overridable with environment variables like so:

```js
const awsConfig = {
  apiVersion: "2015-07-09",
  region: process.env.AWS_REGION || "us-east-1"
};
```

or, alternatively:

```js
// Constants from ENV
const {
  AWS_REGION = 'us-east-1'
} = process.env

const awsConfig = {
  apiVersion: "2015-07-09",
  region: AWS_REGION
}
```

**Comment by niradler** [comment]
Thank you for the feedback! 👍 
for using with node js you can use "setAwsConfig"
for using with the cli you can use the -r <region>
and i also added: 
region: process.env.AWS_DEFAULT_REGION || "us-east-1"

**Comment by Sleavely** [comment]
Awesome, thanks!
